AllCops:
  Include:
    - lib/**/*.rb
    - tool/*.rb
    - spec/**/*.rb
    - Rakefile
    - Gemfile
    - cisco_acl_intp.gemspec
  Exclude:
    - lib/**/parser.rb
    - spec/data/*.rb
MethodLength:
  Max: 15