AllCops:
  NewCops: enable
  SuggestExtensions: false
  Include:
    - lib/**/*.rb
    - tool/*.rb
    - spec/**/*.rb
    - Rakefile
    - Gemfile
    - cisco_acl_intp.gemspec
  Exclude:
    - lib/**/parser.rb
    - spec/data/*.rb
    - vendor/**/*
Metrics/BlockLength:
  Max: 30
  Enabled: false # temporary
Metrics/MethodLength:
  Max: 20
  Enabled: false # temporary
Naming/HeredocDelimiterNaming:
  Enabled: false
