AllCops:
  Includes:
    - lib/**/*.rb
    - tool/*.rb
    - spec/**/*.rb
    - Rakefile
    - Gemfile
    - cisco_acl_intp.gemspec
  Excludes:
    - lib/**/parser.rb
    - spec/data/*.rb
MethodLength:
  Max: 15